### ISSUE TITLE
Check kubernetes changes

### ISSUE THREAD

**Issue by Simonsays095** [aivscovid19/data_pipeline#13]
Associated commit: c81e94d41a16c5345116964369c126bb7317fea4

I made a few changes to improve the automation regarding Pub/Sub topic creation, bigquery setup, and yaml file editing. Please review these changes and close this issue if they're suitable.

Thank you!

**Comment by Simonsays095** [comment]
Added another commit to make one fix to the clean up section, and removed the (accidental) duplication of the readme file contents.
223792f4bb36eb3128815ef9cef893bbee2eb4ef

**Comment by AdrianWR** [comment]
Thank you very much Simon, I checked the commands and it seems pretty clear to me I didn't test the pubsub commands yet, but I plan to do it while I write the shell script to deploy our infrastructure. I submitted a new commit to fix two lines with typos; overall it's pretty great! :)
